#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Mar 14 13:41:13 2020

@author: jonathan gantner
"""

import pandas as pd
import matplotlib.pyplot as plt
import os


exec(open('CSSEGIS.py').read())

# load country meta data
# create country to country code map
country_meta_file = os.path.join('data', 'Comtrade Country Code and ISO list.csv')
country_code_map = pd.read_csv(country_meta_file, index_col=0)
country_code_map = country_code_map['ISO3-digit Alpha']


# load countries population data from 2018
# newest available data from worldbank
population_file = os.path.join('data', 'Worldbank', 'Population',
                               'API_SP.POP.TOTL_DS2_en_csv_v2_821007.csv')
population = pd.read_csv(population_file,
                         skiprows=4, index_col=1)['2018']


# load corona data

# normalize infections by population

covid19_raw = data['confirmed']['data']
covid19_normalized = covid19_raw.div(population)

covid19_normalized[['AUT', 'USA', 'DEU', 'CHN']].plot()
s